services:

  mysql:
    container_name: 'mysql_container'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=ai_agent_spring'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
      - 'MYSQL_USER=${DB_USER}'
    ports:
      - '3307:3306'

  qdrant:
    container_name: 'qdrant_container'
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - 6333:6333
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      QDRANT_API_KEY: ${QDRANT_API_KEY}

  ollama:
    container_name: 'ollama_container'
    image: ollama/ollama:latest
    restart: always
    ports:
      - "11434:11434"
