spring:
  application:
    name: ai-agent

  datasource:
    url: jdbc:mysql://mysql:3307/ai_agent_spring
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  ai:
    vectorstore:
      qdrant:
        host: qdrant
        port: 6333
        api-key: ${QDRANT_API_KEY}
        collection-name: ${QDRANT_COLLECTION_NAME}
        use-tls: false
        initialize-schema: true

    ollama:
      base-url: http://ollama:11434
      embedding:
        model: nomic-embed-text
